{% set name = "torch-harmonics" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/torch-harmonics/archive/refs/tags/v{{ version }}.tar.gz
  sha256: acc9618afd5e14834bc4bed04884fbae42471e76f131bc7003d75da44bfb26de

build:
  # torch-harmonics does not support windows and Python < 3.11.
  skip: true  # [win or py<311]
  ignore_run_exports_from:
    - libcublas-dev    # [cuda_compiler_version != "None"]
    - libcusolver-dev  # [cuda_compiler_version != "None"]
    - libcusparse-dev  # [cuda_compiler_version != "None"]
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION="$PKG_VERSION"  # [not win]
    - set "SETUPTOOLS_SCM_PRETEND_VERSION=%PKG_VERSION%"    # [win]
    - export TORCH_CUDA_ARCH_LIST="8.0;8.6;8.9;9.0a;10.0a;10.3a;12.0+PTX"  # [cuda_compiler_version != "None"]
    - export TORCH_DONT_CHECK_COMPILER_ABI=1                # [cuda_compiler_version != "None"]
    - export TORCH_HARMONICS_BUILD_CUDA_EXTENSION=1         # [cuda_compiler_version != "None"]
    - export MAX_JOBS=2                                     # [cuda_compiler_version != "None"]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cuda') }}   # [cuda_compiler_version != "None"]
    - ninja
  host:
    - python
    - setuptools
    - setuptools-scm
    - libtorch
    - pytorch
    - pip
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - cuda-cudart-dev                           # [cuda_compiler_version != "None"]
    - libcublas-dev                             # [cuda_compiler_version != "None"]
    - libcusolver-dev                           # [cuda_compiler_version != "None"]
    - libcusparse-dev                           # [cuda_compiler_version != "None"]
  run:
    - python
    - numpy >=1.22.4
    - pytorch >=2.9.0 cpu*                      # [cuda_compiler_version == "None"]
    - pytorch >=2.9.0 cuda*                     # [cuda_compiler_version != "None"]

test:
  imports:
    - torch_harmonics
  commands:
    - pip check
    - python -c "from torch_harmonics.disco import optimized_kernels_is_available; assert optimized_kernels_is_available()"
    - python -c "from torch_harmonics.attention import optimized_kernels_is_available; assert optimized_kernels_is_available()"
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/torch-harmonics
  summary: Differentiable signal processing on the sphere for PyTorch.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mwyau
    - isuruf
    - timkpaine
