{% set name = "torch-harmonics" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/torch-harmonics/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 27b5f11d73bda5188bfc949b4d52b4120bbbe75f6e68a7543e103ee285b90b6c

build:
  # Pytorch is not available on conda-forge for windows yet...
  # https://github.com/conda-forge/pytorch-cpu-feedstock/pull/231
  skip: true  # [win]
  # pytorch in conda-forge does not support CUDA 11.8 as of v2.5
  skip: true  # [cuda_compiler_version == "11.8"]
  ignore_run_exports_from:
    - libcublas-dev    # [cuda_compiler_version != "None"]
    - libcusolver-dev  # [cuda_compiler_version != "None"]
    - libcusparse-dev  # [cuda_compiler_version != "None"]
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION="$PKG_VERSION"  # [not win]
    - set "SETUPTOOLS_SCM_PRETEND_VERSION=%PKG_VERSION%"    # [win]
    - export TORCH_CUDA_ARCH_LIST="8.0;8.6;8.9;9.0a;10.0a;10.3a;12.0+PTX"  # [cuda_compiler_version != "None"]
    - export TORCH_DONT_CHECK_COMPILER_ABI=1                # [cuda_compiler_version != "None"]
    - export TORCH_HARMONICS_BUILD_CUDA_EXTENSION=1         # [cuda_compiler_version != "None"]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cuda') }}   # [cuda_compiler_version != "None"]
  host:
    - python
    - setuptools
    - setuptools-scm
    - libtorch
    - pytorch
    - pip
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - cuda-cudart-dev                           # [cuda_compiler_version != "None"]
    - libcublas-dev                             # [cuda_compiler_version != "None"]
    - libcusolver-dev                           # [cuda_compiler_version != "None"]
    - libcusparse-dev                           # [cuda_compiler_version != "None"]
  run:
    - python
    - numpy >=1.22.4
    - pytorch * cpu*          # [cuda_compiler_version == "None"]
    - pytorch * cuda*         # [cuda_compiler_version != "None"]

test:
  imports:
    - torch_harmonics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/torch-harmonics
  summary: Differentiable signal processing on the sphere for PyTorch.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
