{% set name = "torch-harmonics" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torch_harmonics-{{ version }}.tar.gz
  sha256: 082b6fa450252201be3256a58aa37ac6f382b64f076d928eeee8ae94f6dd7245
  patches:
    - fix_numpy.diff

build:
  # Pytorch is not available on conda-forge for windows yet...
  # https://github.com/conda-forge/pytorch-cpu-feedstock/pull/231
  skip: true  # [win]
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION="$PKG_VERSION"  # [not win]
    - set "SETUPTOOLS_SCM_PRETEND_VERSION=%PKG_VERSION%"    # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cuda') }}   # [cuda_compiler_version != "None"]
  host:
    - python
    - setuptools
    - setuptools-scm
    - libtorch
    - pytorch
    - pip
  run:
    - python
    - numpy >=1.22.4
    - pytorch *=cuda*         # [cuda_compiler_version != "None"]

test:
  imports:
    - torch_harmonics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/torch-harmonics
  summary: Differentiable signal processing on the sphere for PyTorch.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
