{% set name = "torch-harmonics" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torch_harmonics-{{ version }}.tar.gz
  sha256: fa7b7a86ded81600e32b55bd0c3c040a5dfef96849305670b7bb24fb96dda2c7

build:
  # Pytorch is not available on conda-forge for windows yet...
  # https://github.com/conda-forge/pytorch-cpu-feedstock/pull/231
  skip: true  # [win]
  # pytorch in conda-forge does not support CUDA 11.8 as of v2.5
  skip: true  # [cuda_compiler_version == "11.8"]
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION="$PKG_VERSION"  # [not win]
    - set "SETUPTOOLS_SCM_PRETEND_VERSION=%PKG_VERSION%"    # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cuda') }}   # [cuda_compiler_version != "None"]
  host:
    - python
    - setuptools
    - setuptools-scm
    - libtorch
    - pytorch
    - pip
  run:
    - python
    - numpy >=1.22.4
    - pytorch * cuda*         # [cuda_compiler_version != "None"]

test:
  imports:
    - torch_harmonics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/torch-harmonics
  summary: Differentiable signal processing on the sphere for PyTorch.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
